services:

  postgres:
    image: postgres:17
    container_name: postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: mediaarchive-api

    depends_on:
      - postgres

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
      Jwt__Key: "${JWT_KEY}"

    ports:
      - "5000:8080"

volumes:
  postgres-data: